# Generated by Django 4.2.1 on 2023-05-23 17:54

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event_app.timestamp')),
                ('event_name', models.CharField(db_index=True, max_length=200)),
                ('event_slug', autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='event_name', unique=True)),
                ('event_start_time', models.DateTimeField(blank=True, null=True)),
                ('event_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=200)),
                ('event_end_time', models.DateTimeField(blank=True, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('event_description', models.CharField(blank=True, max_length=200, null=True)),
                ('max_seats', models.IntegerField(default=0)),
                ('booking_window_start_time', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('event_app.timestamp',),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event_app.timestamp')),
                ('ticket_id', models.BigIntegerField(db_index=True)),
                ('booking_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('event_app.timestamp',),
        ),
    ]
